export default {
  BackpackPlaceholderRemovebgPreview: require('../assets/images/BackpackPlaceholderRemovebgPreview.png'),
  BagNOBG: require('../assets/images/BagNOBG.png'),
  BagForDetailsHighRes1: require('../assets/images/BagForDetailsHighRes1.jpg'),
  ExpensiveButBestRetroVintageBIGSwissArmyMilitaryCanvasBackpackRucksackSaltPepperBag: require('../assets/images/ExpensiveButBestRetroVintageBIGSwissArmyMilitaryCanvasBackpackRucksackSaltPepperBag.png'),
  HeroImageRemovebgPreview: require('../assets/images/HeroImageRemovebgPreview.png'),
  ScrollHorizontal: require('../assets/images/ScrollHorizontal.png'),
  HomeTrendingONGBackpack: require('../assets/images/HomeTrendingONGBackpack.png'),
  ProductCategory: require('../assets/images/ProductCategory.png'),
  ProductCategoryListViewRcommendedRemovebgPreview: require('../assets/images/ProductCategoryListViewRcommendedRemovebgPreview.png'),
  ProductCardDetailRemovebgPreview: require('../assets/images/ProductCardDetailRemovebgPreview.png'),
  ProductCardDetailSuggestedImages: require('../assets/images/ProductCardDetailSuggestedImages.png'),
  ScrollHorizontalSlanted: require('../assets/images/ScrollHorizontalSlanted.png'),
  ShoppingCart: require('../assets/images/ShoppingCart.png'),
  CheckoutCustomIcons2: require('../assets/images/CheckoutCustomIcons2.png'),
  CheckoutCustomIcons1: require('../assets/images/CheckoutCustomIcons1.png'),
  CheckoutCustomIcons3: require('../assets/images/CheckoutCustomIcons3.png'),
  VouchersCustomIcon: require('../assets/images/VouchersCustomIcon.png'),
  VisaIllustration2: require('../assets/images/VisaIllustration2.png'),
  VisaIllustration1: require('../assets/images/VisaIllustration1.png'),
  VisaIllustration3: require('../assets/images/VisaIllustration3.png'),
  OrderConfirmationIllustration: require('../assets/images/OrderConfirmationIllustration.png'),
};
